services:
  web:
    image: nginx:1.23.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysqldata:
